### PR TITLE
Trigger a re-render

### PR DESCRIPTION
**Pull request by bryant1410**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bryant1410** [comment]
@conda-forge-admin please rerender

**Comment by bryant1410** [comment]
Do I still need to bump the build number, even though I have changed nothing?

**Comment by bryant1410** [comment]
And what should I do with the maintainer that doesn't exist?

**Comment by xmnlab** [comment]
> Do I still need to bump the build number, even though I have changed nothing?

good question, I think it is ok to keep the build number as it is. In theory, AFAIK, it will just not update the metadata. but if you want to be sure that any change from this re-render will be reflected on conda-forge, maybe you would want to bump the build number. (I don't have enough knowledge to give a guidance about that, sorry). but feel free to keep the build number as it is :)

> And what should I do with the maintainer that doesn't exist?

could you remove that user please and run again the rerender? thanks!

**Comment by bryant1410** [comment]
@conda-forge-admin please rerender

**Comment by bryant1410** [comment]
BTW, what about doing a periodical re-render? A GitHub action. In my case, I was interested in Python 3.10.

**Comment by xmnlab** [comment]
> BTW, what about doing a periodical re-render? A GitHub action. In my case, I was interested in Python 3.10.

IIRC sometimes the conda-forge has some bots (or one bot) that do something like that in specific cases .. but not sure the conditions

**Comment by xmnlab** [comment]
thanks for working on that @bryant1410 !

**Pull request merged**
