### PR TITLE
Update maintainers list

### PR DESCRIPTION
**Pull request by nnkwame**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nnkwame** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
@kidfisch you need to add your github username here https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/master/recipe/meta.yaml#L56

After that, commit your change and run the rerender it would update all the necessary infrastructure code for it.

sorry for the delay in this review and thank you so much for helping here!

**Comment by nnkwame** [comment]
Thanks for the hint. Will work on this shortly

**Comment by nnkwame** [comment]
I just came across [this](https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#updating-the-maintainer-list) information about the maintainer-update-PR skipping package build.

Should I push an additional empty commit with message “[ci skip] …” or is this unnecessary given the current state of the PR? Thanks.

**Comment by xmnlab** [comment]
@kidfisch thanks for sharing that link. I didn't know that. I think now you don't need to worry about that
it seems that if you had created an issue with that command, it would create a PR similar to this one you created.

Thank you!

**Pull request merged**
