### PR TITLE
update cuda version to 11.5

### PR DESCRIPTION
**Pull request by riturajkumar1468**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by riturajkumar1468** [comment]
@conda-forge-admin, please rerender

**Comment by riturajkumar1468** [comment]
Hey @xmnlab, can we get this merged?

**Comment by xmnlab** [comment]
Lgtm! Thanks for pinging me here. Merging it now

**Comment by riturajkumar1468** [comment]
thanks @xmnlab !!

**Pull request merged**
