### PR TITLE
Update Linux installer to 10.1

### PR DESCRIPTION
**Pull request by carterbox**
First, the Linux installer is kind of broken, we need to add a new
option in order for all of the libraries to be installed. This is
discussed on the nvidia forums [here](https://devtalk.nvidia.com/default/topic/1047903/linux/new-cuda-10-1-run-installer-completely-broken/).

Second, the URL for the installer has changed. The file now has a 'run'
extension.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
I have no idea why the linux version is failing to install. It works on my computer.

Maybe python should be added to the run requirements? Because the post-install script requires python.

**Comment by pearu** [comment]
@andersy005 @xmnlab this can be closed.

**Comment by andersy005** [comment]
Superseded by #16

**Comment by xmnlab** [comment]
thanks for working on that @carterbox !
We just merged another PR that upgrades to 10.1

thanks very much for your help!

**Pull request closed without merging**
