### PR TITLE
Upgrade to cuda 10.0

### PR DESCRIPTION
**Pull request by weiji14**
Hi there, giving this a go at upgrading cudatoolkit from version 9.2 to 10.0!

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Got version_build and driver_version numbers from https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html. Will look into re-rendering using https://conda-forge.org/docs/conda_smithy.html#how-to-re-render

### CODE REVIEW

**Comment by weiji14** [comment]
@conda-forge-admin, please rerender

**Comment by andersy005** [comment]
@weiji14, Thank you! There's a section of the [`cudatoolkit-dev-post-install.py`]( https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/master/recipe/cudatoolkit-dev-post-install.py#L340) that will need to be made robust for the build process to succeed. In this section, we specify a static base url. However, It appears that the base url changes from version to version. For instance:
- cuda 10.0: https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux
- cuda 9.2: https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda_9.2.148_396.37_linux
- cuda 9.1: https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda_9.1.85_387.26_linux
- cuda 9.0: https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_384.81_linux-run
- cuda 8.0 GA2: https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run
- cuda 7.5: http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda_7.5.18_linux.run

It appears that some versions have **Prod** and others have **Prod2**. I don't see a particular pattern here yet. However, I believe this is the root cause of the build process failure.

**Comment by weiji14** [comment]
Hi @andersy005. Good spotting :+1:, I actually just noticed it about the same time you posted the comment! Let's see if the CI passes now.

**Comment by weiji14** [comment]
Looks good to me. Review and merge?

**Comment by andersy005** [comment]
@scopatz, what are your thoughts on this? Do you have any suggestion on how to handle the base url issue? I don't see any particular pattern they are using for **prod** or **prod2**. I can't think of any better & automated approach other than hard-coding this whenever there is a new release.

**Pull request merged**
