### PR TITLE
Update version to 11.0.3

### PR DESCRIPTION
**Pull request by AgrawalAmey**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- Since NVIDIA has dropped support of CUDA for osx, I have removed that osx build.

### CODE REVIEW

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
@andersy005 @scopatz @xmnlab can you please review this PR. Thank you!

**Comment by xmnlab** [comment]
LGTM. thanks @AgrawalAmey . 

@andersy005 @scopatz any thought about this PR?

**Comment by isuruf** [comment]
You can add
```yaml
os_version:
  linux_64: cos7
```
to get a docker image with updated glibc.

**Comment by AgrawalAmey** [comment]
Thanks @isuruf for the pointer. I have updated the PR.

@xmnlab Thanks for the review. Since the cuda ecosystem is very sensitive to minor versions as well, can we also publish packages for versions 11.0 and 11.1? I am not sure about the convention around it, do we create three PR? starting from 11.0?

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by Hoeze** [comment]
> @xmnlab Thanks for the review. Since the cuda ecosystem is very sensitive to minor versions as well, can we also publish packages for versions 11.0 and 11.1? I am not sure about the convention around it, do we create three PR? starting from 11.0?

11.1 and 11.2 would be highly appreciated :)

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
@xmnlab I have changed the version here to 11.0.2 from 11.2 and have created separate PRs for 11.1 and 11.2. (https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/31 , https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/32).

**Comment by AgrawalAmey** [comment]
@xmnlab, @scopatz, @andersy005 can we close on this, if all looks good. Thanks a lot!

**Comment by AgrawalAmey** [comment]
@xmnlab, @scopatz, @andersy005 a gentle reminder to review these PRs. Thanks a lot!

**Comment by Hoeze** [comment]
Maybe it would be good to give @AgrawalAmey merge privileges to this repo?
(@xmnlab @scopatz @andersy005)

Just as a note, why these pull requests are really needed to be merged:
Two of my colleagues invested the whole last week on installing/re-compiling Cuda, PyTorch, Tensorflow, etc. since the CUDA versions in conda are not up-to-date.

Thanks a lot!

**Comment by xmnlab** [comment]
sorry for the delay here! @AgrawalAmey thanks for all the work you are doing here.

@Hoeze I agree with you. @AgrawalAmey could you add yourself here https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/30/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR50 ?


so for the next PRs you will have permissions to move things forward :)

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
Thanks a lot, @xmnlab, @Hoeze. I added my id in meta.yaml and ran render, is that all we need to do?

**Comment by xmnlab** [comment]
LGTM! thanks @AgrawalAmey !

**Comment by AgrawalAmey** [comment]
Thanks @xmnlab!

**Comment by Hoeze** [comment]
Thanks so much for updating @AgrawalAmey and merging @xmnlab!

**Pull request merged**
