### PR TITLE
Fix python

### PR DESCRIPTION
**Pull request by andersy005**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

@<space/>conda-forge-admin, please rerender

### CODE REVIEW

**Comment by andersy005** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
@andersy005 

you can just ignore that now (https://github.com/conda-forge/gperftools-feedstock/pull/2#issuecomment-413913998)

**Comment by andersy005** [comment]
@xmnlab, Thank you!

**Comment by andersy005** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
