### PR TITLE
Enable copying files if dst directory already exists

### LINKED ISSUE #18: Updating cudatoolkit-dev fails: File exists: '/path/to/pkgs/cuda-toolkit'
Issue:
`conda update -c conda-forge cudatoolkit-dev` fails:
```
...
Running Post installation
downloading https://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_rhel6.run to /home/pearu/mconda3/envs/cudatoolkit-test/pkgs/cudatoolkit-dev/cuda_10.1.243_418.87.00_rhel6.run
Extracting on Linux
Try using /tmp/tmp_yq6alf_/cuda-linux.10.1.243-26907403.run

stderr: Traceback (most recent call last):
  File "/home/pearu/mconda3/envs/cudatoolkit-test/bin/cudatoolkit-dev-post-install.py", line 301, in <module>
    _main()
  File "/home/pearu/mconda3/envs/cudatoolkit-test/bin/cudatoolkit-dev-post-install.py", line 297, in _main
    extractor.extract()
  File "/home/pearu/mconda3/envs/cudatoolkit-test/bin/cudatoolkit-dev-post-install.py", line 168, in extract
    self.copy_files(toolkitpath, self.src_dir)
  File "/home/pearu/mconda3/envs/cudatoolkit-test/bin/cudatoolkit-dev-post-install.py", line 124, in copy_files
    source, destination, symlinks=True, ignore_dangling_symlinks=True
  File "/home/pearu/mconda3/lib/python3.7/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/home/pearu/mconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/pearu/mconda3/envs/cudatoolkit-test/pkgs/cuda-toolkit'

return code: 1

()
```

### LINKED ISSUE #19: installation stuck on "Executing transaction"
Issue: Installation with conda stuck on "Executing transaction". After hitting `C-c` I get 
````
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::cudatoolkit-dev-10.1.243-h516909a_1'.
Rolling back transaction: done

CondaSignalInterrupt: Signal interrupt SIGINT
()
````

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at /home/hovnatan/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                0.24.0                py37_1003    conda-forge
astroid                   2.3.0                    py37_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
binutils_impl_linux-64    2.31.1               h6176602_1  
binutils_linux-64         2.31.1               h6176602_9    conda-forge
boost                     1.70.0           py37h9de70de_1    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
cmake                     3.15.3               hf94ab9c_0    conda-forge
conda                     4.7.12                   py37_0    conda-forge
conda-package-handling    1.6.0            py37h516909a_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
cudatoolkit               10.0.130                      0  
curl                      7.65.3               hf8cf82a_0    conda-forge
cython                    0.29.13          py37he1b5a44_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
ffmpeg                    4.1.3                h167e202_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_9    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.9                h516909a_0    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
greenlet                  0.4.15           py37h516909a_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_9    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.5                      281  
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21                   py37_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
lazy-object-proxy         1.4.2            py37h516909a_0    conda-forge
libarchive                3.4.0                hb44662c_0    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libclang                  9.0.0                hc9558a2_0    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdrm-cos6-x86_64        2.4.65               hd39d64f_0  
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
liblapacke                3.8.0               12_openblas    conda-forge
libllvm9                  9.0.0                hc9558a2_2    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libselinux-cos6-x86_64    2.0.94               hc7b3062_0  
libsepol-cos6-x86_64      2.0.41               h6e2433f_0  
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libuv                     1.31.0               h516909a_0    conda-forge
libwebp                   1.0.2                h576950b_1    conda-forge
libx11-common-cos6-x86_64 1.6.4                h023ea50_0  
libx11-cos6-x86_64        1.6.4                h64a1553_0  
libxcb                    1.13              h14c3975_1002    conda-forge
libxdamage-cos6-x86_64    1.1.3                h8e310ee_0  
libxfixes-cos6-x86_64     5.0.3                h3a64028_0  
libxkbcommon              0.8.4                h516909a_0    conda-forge
libxml2                   2.9.9                hee79883_5    conda-forge
libxxf86vm-cos6-x86_64    1.1.3                h3cd9653_0  
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mesa-dri-drivers-cos6-x86_64 11.0.7               h6ae8bd2_0  
mesa-dri1-drivers-cos6-x86_64 7.11                 hd08e721_0  
mesa-libgl-cos6-x86_64    11.0.7               h045e36e_0  
mkl                       2019.5                      281  
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.2                he80fd80_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
neovim                    0.3.1                    py37_0    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
ninja                     1.9.0                h6bb024c_0    conda-forge
nspr                      4.20              hf484d3e_1000    conda-forge
nss                       3.46                 he751ad9_0    conda-forge
numpy                     1.17.2           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.7                h6e990d7_1    conda-forge
opencv                    4.1.1            py37h0cc45ee_2    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
parso                     0.5.1                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.1.0            py37h6b7be26_1    conda-forge
pip                       19.2.3                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pudb                      2019.1                   py37_0    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pylint                    2.4.1                    py37_0    conda-forge
pynvim                    0.3.2                    py37_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
qt                        5.12.5               h0c104cb_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hcee41ef_1    conda-forge
sympy                     1.4                      py37_0    conda-forge
tbb                       2019.8               hc9558a2_0    conda-forge
tbb-devel                 2019.8               hc9558a2_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
torchvision               0.4.0                py37_cu100    pytorch
tqdm                      4.36.1                     py_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
urwid                     2.0.1           py37h14c3975_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
wrapt                     1.11.2           py37h516909a_0    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.8                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
yapf                      0.28.0                     py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```

     active environment : base
    active env location : /home/hovnatan/miniconda3
            shell level : 1
       user config file : /home/hovnatan/.condarc
 populated config files : /home/hovnatan/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/hovnatan/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/fastai/linux-64
                          https://conda.anaconda.org/fastai/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/hovnatan/miniconda3/pkgs
                          /home/hovnatan/.conda/pkgs
       envs directories : /home/hovnatan/miniconda3/envs
                          /home/hovnatan/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/5.3.1-arch1-1-ARCH arch/rolling glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False



```
</details>

### PR DESCRIPTION
**Pull request by andersy005**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #19, Fixes #18

### CODE REVIEW

**Comment by andersy005** [comment]
@conda-forge-admin, please rerender

**Comment by ManifoldFR** [comment]
Any progress on merging this pull request?

**Comment by scopatz** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
it seems that the original branch doesn't exist anymore.

**Comment by xmnlab** [comment]
Continued at https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/35

**Pull request closed without merging**
