### PR TITLE
[WIP] Update toolkit version 10.2.89

### LINKED ISSUE #23: CUDA 10.2?
Hi,

are you planning on updating this feedstock to provide CUDA 10.2.89?

Thanks a lot for considering,
Axel

### PR DESCRIPTION
**Pull request by asford**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Resolves #23

### CODE REVIEW

**Comment by asford** [comment]
@conda-forge-admin, please rerender

**Comment by hexfaker** [comment]
Any progress on this?

**Comment by hadim** [comment]
Friendly bump here to see if this PR is still of interest to some.

**Comment by scopatz** [comment]
FWIW This feedstock should probably be archived at this point

**Comment by hadim** [comment]
What package are we supposed to use to build against cuda on conda forge then?

**Comment by scopatz** [comment]
see the nvcc package and the cudatoolkit package

**Comment by dirkgr** [comment]
Neither of them installs a working NVCC or headers. This is the package that does.

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by csukuangfj** [comment]
Any progress?

I also need CUDA 10.2

**Comment by AgrawalAmey** [comment]
@xmnlab should we close this PR now as we have already moved to CUDA 11 on the main branch?

**Comment by xmnlab** [comment]
I am closing this PR for now. if there is any need to have a build for 10.X series, let me know and I will create a new branch for that.  thanks!

**Pull request closed without merging**
