### PR TITLE
Avoid terminal window popup.

### PR DESCRIPTION
**Pull request by pearu**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes issue #7

### CODE REVIEW

**Comment by pearu** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
@andersy005 @xmnlab, please review.

**Review by andersy005 — APPROVED** [review]
Looks great!

**Review by xmnlab — APPROVED** [review]
LGTM @pearu 

feel free to add your user into `recipe-maintainers`

**Pull request merged**
