### PR TITLE
Update version to 11.2

### PR DESCRIPTION
**Pull request by AgrawalAmey**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by Hoeze** [comment]
@AgrawalAmey @xmnlab Would you mind also merging the two newer versions 11.1 and 11.2?

**Comment by AgrawalAmey** [comment]
@Hoeze there seems to be an issue with this build where it is can only be installed in python 3.9. I was planning to merge the other PRs once we have a resolution for this problem.

**Comment by Hoeze** [comment]
Alright, thanks for the note :+1:

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
@xmnlab we can merge this right after #31

**Comment by xmnlab** [comment]
@AgrawalAmey #31 is merged
this PR now will need a rebase/update, thanks!

**Comment by AgrawalAmey** [comment]
@xmnlab oh sorry, resolved the conflict. Thank you!

**Comment by AgrawalAmey** [comment]
@xmnlab merging this now. Thank you!

**Pull request merged**
